export type RangeBitrixType = {
    "ID": number,
    "IBLOCK_ID": string,
    "NAME": string,
    "CREATED_BY": string,
    "BP_PUBLISHED": string,
    "TIMESTAMP_X": Date,
    "MODIFIED_BY": string,
    "USER_NAME": string,
    "PROPERTY_689"?: string | Record<string, string>,
    "PROPERTY_771"?: string | Record<string, string>,
    "PROPERTY_681"?: string | Record<string, string>,
    "PROPERTY_459"?: string | Record<string, string>,
    "PROPERTY_935"?: string | Record<string, string>,
    "PROPERTY_691"?: string | Record<string, string>,
    "PROPERTY_693"?: string | Record<string, string>,
    "PROPERTY_695"?: string | Record<string, string>,
    "PROPERTY_697"?: string | Record<string, string>,
}
